# Generated by Django 3.1.3 on 2021-01-15 00:51

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_svgmap', '0002_size_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
